FROM zabbix/zabbix-server-mysql:alpine-6.0-latest

# Switch to root user to install necessary packages
USER root

# Install Python and pip
RUN apk add --no-cache python3 py3-pip

# Install Zabbix API Python client
RUN pip3 install py-zabbix

# Switch back to zabbix user
USER zabbix

# Copy Zabbix API script
COPY zabbix-setup.py /usr/local/bin/zabbix_setup.py
RUN chmod +x /usr/local/bin/zabbix_setup.py

# Use default entrypoint
ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/docker-entrypoint.sh"]