FROM zabbix/zabbix-web-apache-mysql:alpine-6.0-latest

# Copy Apache configuration
COPY apache-config /etc/apache2/sites-enabled

# Set up entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Use custom entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]