version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: zabbix-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-server
    container_name: zabbix-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_SERVER_HOST: zabbix-server
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-net

  zabbix-web:
    build:
      context: .
      dockerfile: Dockerfile.zabbix-web
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Warsaw
    volumes:
      - ./apache-config:/etc/apache2/sites-enabled
    networks:
      - zabbix-net
    ports:
      - "80:80"

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix_server_data:
  db_data: