version: '3.8'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-6.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
    volumes:
      - /path/to/ssl/certs:/etc/apache2/ssl
      - ./apache-config:/etc/apache2/sites-enabled
    networks:
      - zabbix-net
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mariadb:10.5
    container_name: zabbix-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix_server_data:
  db_data:
